[tool.poetry]
name = "wris-india"
version = "0.1.0"
description = "Datasets scrapers, cleaning scripts, and documentation for wris datasets"
authors = ["Surya Kandukuri"]

[tool.poetry.dependencies]
python = "^3.7"
python-dotenv = "^0.13.0"
click = "^7.1.2"
pandas = "^1.0.5"
numpy = "^1.19.0"
selenium = "^3.141.0"
bs4 = "^0.0.1"
html5lib = "^1.1"
webdriver-manager = "^3.4.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
