[tool.poetry]
name = "Union Budget"
version = "0.1.0"
description = "consolidate union government budgets for past 5 years"
authors = ["Ujjawal, Vijay"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
